# HR analytics

In [2]:
import pandas as pd
txns=pd.read_csv("ibm.csv")
txns.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

What is the overall attrition rate in the company?

Which department has the highest attrition rate?

What is the average age of employees who left the company versus those who stayed?

Does distance from home impact attrition?

How does attrition vary by gender?

What is the relationship between job satisfaction and attrition?

Which job roles have the highest attrition rates?

Does education level influence attrition?

Are employees with more training less likely to leave?

Is overtime a major contributor to attrition?

What is the average monthly income of employees who left compared to those who stayed?

How does attrition vary by marital status?

What is the relationship between total working years and attrition?

Which age group experiences the most attrition?

How does environment satisfaction relate to attrition?

What is the distribution of job levels among employees who left?

Are employees with higher performance ratings less likely to leave?

How does business travel frequency affect attrition?

Which department pays the highest average monthly income?

How does attrition vary by job involvement level?

Do employees with stock options stay longer in the company?

Is there a relationship between salary hike percentage and attrition?

How many employees work overtime in each department?

What is the correlation between years at the company and years since last promotion?

Do employees with longer tenure tend to have higher satisfaction scores?

How many employees have worked in multiple companies before joining?

How does attrition vary based on work-life balance score?

What is the average monthly income per job role?

Which education field has the most employees?

How does attrition vary across different education fields?

What is the average number of years since last promotion by department?

Are employees with more training sessions more satisfied?

How does performance rating affect salary hikes?

Do employees with high environment satisfaction also report high job satisfaction?

What is the gender ratio across different job roles?

What is the average age per job role?

Which business travel category has the highest average monthly income?

Do employees with higher job involvement have better performance ratings?

How many employees are in each job level?

What is the correlation between monthly income and total working years?

Which department has the most employees?

What is the distribution of job satisfaction scores?

What is the trend of attrition across different job roles and job levels?

What is the average work-life balance score across departments?

Which age group has the highest number of managers or executives?

Are older employees more satisfied with their work environment?

What is the most common business travel frequency among top performers?

How does training frequency affect job satisfaction?

Which combination of factors (age, job role, income) is most linked to attrition?

Can we predict potential attrition based on salary, satisfaction, and working years (for ML modeling)?